-- Criação da tabela Especie com as seguintes colunas (id - primary key, nome - não nulo)
CREATE TABLE Oracle18c.Especie(
    especie_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(50) NOT NULL,
    PRIMARY KEY(especie_id)
);
-- Criação da tabela Dono com as seguintes colunas (id - primary key, nome - não nulo, cpf - único, fone - sem restrição)
CREATE TABLE Oracle18c.Dono(
    dono_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(50) NOT NULL,
    cpf NUMBER NOT NULL UNIQUE,
    fone NUMBER,
    PRIMARY KEY(dono_id)
);
-- Criação da tabela Animal com as seguintes colunas (id - primary key, nome - não nulo, raca - chave estrangeira da tabela espécie)
CREATE TABLE Oracle18c.Animal (
    animal_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(50) NOT NULL,
    raca NUMBER NOT NULL ,
    PRIMARY KEY(animal_id),
    FOREIGN KEY(raca) REFERENCES Oracle18c.Especie(especie_id)
);